# Generated by Django 3.1.7 on 2021-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='itemId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderId',
            field=models.IntegerField(),
        ),
    ]
