# Generated by Django 3.1.7 on 2021-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('order', 'ordered'), ('cancel', 'canceled')], default='order', max_length=6),
        ),
    ]
