# Generated by Django 3.1.7 on 2021-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.FileField(default='invoice/default.pdf', upload_to='invoice/'),
        ),
    ]
